-- Базовая схема Task Tracker.
-- Задачи, справочник тегов и связь многие-ко-многим между ними.

-- Триграммный поиск подстроки в заголовке (ILIKE '%...%').
-- pg_trgm — доверенное расширение начиная с PostgreSQL 13,
-- владельцу базы прав на его установку достаточно.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------------
-- tasks — задачи
-- ---------------------------------------------------------------------------
CREATE TABLE tasks (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(120) NOT NULL,
    description TEXT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'TODO',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Список статусов дублирует Java-enum TaskStatus: база не даст записать
    -- значение, которого нет в коде, даже в обход приложения.
    CONSTRAINT chk_tasks_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),

    -- Заголовок из одних пробелов недопустим (аналог @NotBlank).
    CONSTRAINT chk_tasks_title_not_blank CHECK (btrim(title) <> '')
);

COMMENT ON TABLE tasks IS 'Задачи трекера';

-- ---------------------------------------------------------------------------
-- tags — справочник тегов
-- ---------------------------------------------------------------------------
CREATE TABLE tags (
    id   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT uq_tags_name UNIQUE (name),
    CONSTRAINT chk_tags_name_not_blank CHECK (btrim(name) <> '')
);

COMMENT ON TABLE tags IS 'Справочник тегов, имя уникально';

-- ---------------------------------------------------------------------------
-- task_tags — связь многие-ко-многим
-- ---------------------------------------------------------------------------
CREATE TABLE task_tags (
    task_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,

    -- Составной первичный ключ: одна и та же пара не может повториться.
    CONSTRAINT pk_task_tags PRIMARY KEY (task_id, tag_id),

    -- Удаление задачи забирает с собой её связи, сами теги остаются.
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_tags_tag  FOREIGN KEY (tag_id)  REFERENCES tags (id)  ON DELETE CASCADE
);

COMMENT ON TABLE task_tags IS 'Связь задач и тегов (many-to-many)';

-- ---------------------------------------------------------------------------
-- Индексы под сценарии фильтрации из GET /api/tasks
-- ---------------------------------------------------------------------------

-- Сортировка по дате создания без фильтров (список по умолчанию).
CREATE INDEX idx_tasks_created_at ON tasks (created_at DESC);

-- Фильтр по статусу вместе с сортировкой по дате — самый частый запрос.
-- Отдельный индекс только по status не нужен: составной покрывает и его.
CREATE INDEX idx_tasks_status_created_at ON tasks (status, created_at DESC);

-- Поиск по части заголовка. Обычный btree для LIKE '%...%' бесполезен,
-- поэтому GIN по триграммам.
CREATE INDEX idx_tasks_title_trgm ON tasks USING gin (title gin_trgm_ops);

-- Первичный ключ task_tags покрывает поиск по task_id (он левая колонка),
-- а для обратного направления «найти задачи по тегу» нужен свой индекс.
CREATE INDEX idx_task_tags_tag_id ON task_tags (tag_id);
